### ISSUE TITLE
URLError when loading ComPath

### ISSUE THREAD

**Issue by mali-git** [SmartDataAnalytics/BioKEEN#20]
> Traceback (most recent call last):
  File "/Users/mehdi/virtual_envs/iswc/bin/biokeen", line 10, in <module>
    sys.exit(main())
  File "/Users/mehdi/virtual_envs/iswc/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mehdi/virtual_envs/iswc/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/mehdi/virtual_envs/iswc/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mehdi/virtual_envs/iswc/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mehdi/virtual_envs/iswc/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/mehdi/virtual_envs/iswc/lib/python3.6/site-packages/biokeen/cli/cli.py", line 52, in start
    config = prompt_biokeen_config(connection=connection, rebuild=rebuild)
  File "/Users/mehdi/virtual_envs/iswc/lib/python3.6/site-packages/biokeen/cli/prompts.py", line 42, in prompt_biokeen_config
    for name in select_bio2bel_repository()
  File "/Users/mehdi/virtual_envs/iswc/lib/python3.6/site-packages/biokeen/cli/prompts.py", line 42, in <listcomp>
    for name in select_bio2bel_repository()
  File "/Users/mehdi/virtual_envs/iswc/lib/python3.6/site-packages/biokeen/content.py", line 73, in install_bio2bel_module
    graph = manager.to_bel()
  File "/Users/mehdi/virtual_envs/iswc/lib/python3.6/site-packages/compath_resources/manager.py", line 28, in to_bel
    return get_bel()
  File "/Users/mehdi/virtual_envs/iswc/lib/python3.6/site-packages/compath_resources/manager.py", line 38, in get_bel
    df = get_df()
  File "/Users/mehdi/virtual_envs/iswc/lib/python3.6/site-packages/compath_resources/parser.py", line 24, in get_df
    pd.read_csv(KEGG_WIKIPATHWAYS_URL),
  File "/Users/mehdi/virtual_envs/iswc/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/mehdi/virtual_envs/iswc/lib/python3.6/site-packages/pandas/io/parsers.py", line 413, in _read
    filepath_or_buffer, encoding, compression)
  File "/Users/mehdi/virtual_envs/iswc/lib/python3.6/site-packages/pandas/io/common.py", line 202, in get_filepath_or_buffer
    req = _urlopen(filepath_or_buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>

**Comment by cthoyt** [comment]
What's the code you have to run to get this error?

**Comment by mali-git** [comment]
> What's the code you have to run to get this error?

I started BioKEEN through the CLI `biokeen start` and wanted to access ComPath.

**Comment by cthoyt** [comment]
it worked for me with a clean install. This error looks like its due to a network connection
