### ISSUE TITLE
KEGG is empty

### ISSUE THREAD

**Issue by mali-git** [SmartDataAnalytics/BioKEEN#21]
After executing `biokeen start`and selecting KEGG as DB, I got following exception:

> Traceback (most recent call last):
  File "/Users/mehdi/virtual_envs/BioKEEN/bin/biokeen", line 11, in <module>
    load_entry_point('biokeen', 'console_scripts', 'biokeen')()
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/mehdi/PycharmProjects/BioKEEN/src/biokeen/cli/cli.py", line 57, in start
    do_prompt_bio2bel=(not no_prompt_bio2bel),
  File "/Users/mehdi/PycharmProjects/BioKEEN/src/biokeen/cli/prompts.py", line 44, in prompt_biokeen_config
    for name in select_bio2bel_repository()
  File "/Users/mehdi/PycharmProjects/BioKEEN/src/biokeen/cli/prompts.py", line 44, in <listcomp>
    for name in select_bio2bel_repository()
  File "/Users/mehdi/PycharmProjects/BioKEEN/src/biokeen/content.py", line 47, in install_bio2bel_module
    graph = from_json_path(json_path)
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/pybel/io/nodelink.py", line 99, in from_json_path
    return from_json_file(f, check_version=check_version)
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/pybel/io/nodelink.py", line 110, in from_json_file
    return from_json(graph_json_dict, check_version=check_version)
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/pybel/io/nodelink.py", line 87, in from_json
    graph = node_link_graph(graph_json_dict)
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/pybel/io/nodelink.py", line 179, in node_link_graph
    _dsl = parse_result_to_dsl(node_data)
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/pybel/tokens.py", line 43, in parse_result_to_dsl
    return _simple_po_to_dict(tokens)
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/pybel/tokens.py", line 106, in _simple_po_to_dict
    name=tokens[NAME],
KeyError: 'name'

**kegg.keen.summary.json**  shows 0 entities and 0 relations

**Comment by cthoyt** [comment]
this one looks like more of a problem...
