### ISSUE TITLE
Exception while Accessing miRTarBase

### ISSUE THREAD

**Issue by mali-git** [SmartDataAnalytics/BioKEEN#22]
After selecting [mirtarbase](https://github.com/bio2bel/mirtarbase) from the CLI, I got following exception:

```python-traceback
Traceback (most recent call last):
  File "/Users/mali/development/virtual_envs/biokeen/bin/biokeen", line 10, in <module>
    sys.exit(main())
  File "/Users/mali/development/virtual_envs/biokeen/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mali/development/virtual_envs/biokeen/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/mali/development/virtual_envs/biokeen/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mali/development/virtual_envs/biokeen/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mali/development/virtual_envs/biokeen/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/mali/development/virtual_envs/biokeen/lib/python3.7/site-packages/biokeen/cli/cli.py", line 57, in start
    do_prompt_bio2bel=(not no_prompt_bio2bel),
  File "/Users/mali/development/virtual_envs/biokeen/lib/python3.7/site-packages/biokeen/cli/prompts.py", line 44, in prompt_biokeen_config
    for name in select_bio2bel_repository()
  File "/Users/mali/development/virtual_envs/biokeen/lib/python3.7/site-packages/biokeen/cli/prompts.py", line 44, in <listcomp>
    for name in select_bio2bel_repository()
  File "/Users/mali/development/virtual_envs/biokeen/lib/python3.7/site-packages/biokeen/content.py", line 73, in install_bio2bel_module
    graph = manager.to_bel()
  File "/Users/mali/development/virtual_envs/biokeen/lib/python3.7/site-packages/bio2bel_mirtarbase/manager.py", line 369, in to_bel
    for mirna, interaction, evidence in tqdm(self.get_mirna_interaction_evidences(), total=self.count_evidences(),
  File "/Users/mali/development/virtual_envs/biokeen/lib/python3.7/site-packages/bio2bel_mirtarbase/manager.py", line 345, in get_mirna_interaction_evidences
    .join(Interaction) \
  File "/Users/mali/development/virtual_envs/biokeen/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2235, in join
    from_joinpoint=from_joinpoint,
  File "<string>", line 2, in _join
  File "/Users/mali/development/virtual_envs/biokeen/lib/python3.7/site-packages/sqlalchemy/orm/base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "/Users/mali/development/virtual_envs/biokeen/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2414, in _join
    left, right, onclause, prop, create_aliases, outerjoin, full
  File "/Users/mali/development/virtual_envs/biokeen/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2437, in _join_left_to_right
    ) = self._join_determine_implicit_left_side(left, right, onclause)
  File "/Users/mali/development/virtual_envs/biokeen/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2568, in _join_determine_implicit_left_side
    "Can't determine which FROM clause to join "
sqlalchemy.exc.InvalidRequestError: Can't determine which FROM clause to join from, there are multiple FROMS which can join to this entity. Try adding an explicit ON clause to help resolve the ambiguity.
```

**Comment by cthoyt** [comment]
This repo is updated on PyPI and should be working now. Honestly not really sure what was causing the problem, though
