### ISSUE TITLE
ImportError: cannot import name 'VERSION' from 'pykeen.constants'

### ISSUE THREAD

**Issue by Jeffrey-Sardina** [SmartDataAnalytics/BioKEEN#30]
Hello,

I attempted to install and run BioKEEN today, but I have ben unable to start the program. When I execute "biokeen" in the terminal, I get the eror "ImportError: cannot import name 'VERSION' from 'pykeen.constants'". I have included my commands and error outputs below.

**In Python 3,.8.6, on PowerShell, I ran**
```
$ pip install biokeen
$ biokeen
```

**Which resulted in the error**
```
Traceback (most recent call last):
  File "c:\users\USER\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\USER\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\Scripts\biokeen.exe\__main__.py", line 4, in <module>
  File "c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\biokeen\cli\__init__.py", line 5, in <module>
    from .cli import main  # noqa: 401
  File "c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\biokeen\cli\cli.py", line 24, in <module>
    from pykeen.constants import VERSION as PYKEEN_VERSION
ImportError: cannot import name 'VERSION' from 'pykeen.constants' (c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\pykeen\constants.py)
```

**I attempted this in WSL as well. My python3 points to python v3.6.9.** 
```
$ pip3 install biokeen
$ biokeen
```

**Which is resulting in the equivalant error:**
```
Traceback (most recent call last):
  File "/home/USER/.local/bin/biokeen", line 
5, in <module>
    from biokeen.cli import main
  File "/home/USER/.local/lib/python3.6/site-packages/biokeen/cli/__init__.py", line 5, in <module>
    from .cli import main  # noqa: 401
  File "/home/USER/.local/lib/python3.6/site-packages/biokeen/cli/cli.py", line 24, in <module>
    from pykeen.constants import VERSION as PYKEEN_VERSION
ImportError: cannot import name 'VERSION'   
```

I would greatly appreciate any advice you have in terms of resolving this issue.

Thank you,
--Jeffrey Sardina

**Comment by cthoyt** [comment]
Hi @Jeffrey-Sardina, most of the biokeen functionality has been moved over to the PyKEEN repository. Based on your issue in the other repo, I think you figured that out already. Please let me know if there's some specific biokeen functionality - basially all that's left is the interactive CLI
