### ISSUE TITLE
mirtarbase

### ISSUE THREAD

**Issue by mali-git** [SmartDataAnalytics/BioKEEN#8]
"bio2bel_mirtarbase does not produce BEL"

**Comment by cthoyt** [comment]
I still think we've already fixed this, and it's a problem with an old version of the installation.

I just added a piece of logging that looks up the version number of the currently installed `bio2bel_mirtarbase` and prints it. Please send the output of `pip freeze` and the error message in full.

**Comment by mali-git** [comment]
> I still think we've already fixed this, and it's a problem with an old version of the installation.
> 
> I just added a piece of logging that looks up the version number of the currently installed `bio2bel_mirtarbase` and prints it. Please send the output of `pip freeze` and the error message in full.

### Output of pip freeze:

alabaster==0.7.12
asn1crypto==0.24.0
Babel==2.6.0
bio2bel==0.2.0
bio2bel-hgnc==0.2.0
bio2bel-mirtarbase==0.1.2
bio2bel-wikipathways==0.2.0
-e git+https://github.com/SmartDataAnalytics/BioKEEN.git@ab7287ca6b2aa4a6a00621b34ee1d9ef60e89181#egg=biokeen
bumpversion==0.5.3
certifi==2018.10.15
cffi==1.11.5
chardet==3.0.4
Click==7.0
click-plugins==1.0.4
compath-resources==0.0.7
compath-utils==0.2.1
configparser==3.5.0
cryptography==2.4.2
dataclasses==0.6
decorator==4.3.0
docutils==0.14
easy-config==0.2.0
enum34==1.1.6
filelock==3.0.10
flasgger==0.9.2
Flask==1.0.2
Flask-Cors==3.0.7
idna==2.7
ijson==2.3
imagesize==1.1.0
isodate==0.6.0
itsdangerous==1.1.0
Jinja2==2.10
jsonschema==2.6.0
MarkupSafe==1.1.0
mistune==0.8.4
mock==2.0.0
ndex2==2.0.0.8
networkx==2.2
numpy==1.15.4
packaging==18.0
pandas==0.23.4
passlib==1.7.1
pbr==5.1.1
Pillow==5.3.0
pluggy==0.8.0
prompt-toolkit==2.0.7
py==1.7.0
PyBEL==0.12.2
pycparser==2.19
Pygments==2.2.0
PyHGNC==0.2.4
pykeen==0.0.13.dev0
PyMySQL==0.9.2
pyparsing==2.3.0
pysolr==3.8.1
python-dateutil==2.7.5
pytz==2018.7
PyYAML==3.13
rdflib==4.2.2
requests==2.20.1
requests-file==1.4.3
requests-toolbelt==0.8.0
scikit-learn==0.19.1
scipy==1.1.0
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.8.2
sphinxcontrib-websupport==1.1.0
SQLAlchemy==1.2.14
toml==0.10.0
torch==0.4.0
torchvision==0.2.1
tox==3.5.3
tqdm==4.28.1
urllib3==1.24.1
virtualenv==16.1.0
wcwidth==0.1.7
Werkzeug==0.14.1
WTForms==2.2.1
xlrd==1.1.0

**Error message:**

> 🍩 imported bio2bel_mirtarbase
Traceback (most recent call last):
  File "/Users/mehdi/virtual_envs/BioKEEN/bin/biokeen", line 11, in <module>
    load_entry_point('biokeen', 'console_scripts', 'biokeen')()
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/mehdi/PycharmProjects/BioKEEN/src/biokeen/cli.py", line 106, in start
    config = prompt_config(connection, rebuild)
  File "/Users/mehdi/PycharmProjects/BioKEEN/src/biokeen/cli.py", line 52, in prompt_config
    config[TRAINING_SET_PATH] = install_bio2bel_module(name=database_name, connection=connection, rebuild=rebuild)
  File "/Users/mehdi/PycharmProjects/BioKEEN/src/biokeen/cli_utils/bio_2_bel_utils.py", line 71, in install_bio2bel_module
    version = pkg_resources.get_distribution("construct").version
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/pkg_resources/__init__.py", line 479, in get_distribution
    dist = get_provider(dist)
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/pkg_resources/__init__.py", line 355, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/mehdi/virtual_envs/BioKEEN/lib/python3.6/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'construct' distribution was not found and is required by the application

**Comment by cthoyt** [comment]
Okay. We still need to make a new release for miRTarBase, but for some reason the unit tests aren't passing anymore :/
